import 'package:flutter/material.dart';
import 'package:lettutor/src/constants/routes.dart';
import 'package:lettutor/src/features/courses/courses_page.dart';
import 'package:lettutor/src/features/homepage/views/homepage.dart';
import 'package:lettutor/src/features/schedules/schedule_page.dart';
import 'package:lettutor/src/features/settings/settings_page.dart';
import 'package:lettutor/src/features/tutor/search_tutor/views/tutor_search_page.dart';
import 'package:lettutor/src/providers/auth_provider.dart';
import 'package:provider/provider.dart';